name: Build and Extract Files from Docker Container

on:
  push:
    branches:
      - master

jobs:
  build-and-extract-files:
    runs-on: ubuntu-latest
    if: ${{ false }}  # Set condition to false to make the workflow inactive

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Extract Files from Docker Container
        run: |
          # Build the Docker image from the Dockerfile in the repository
          docker build \
            --build-arg CPU_CORES=$(nproc) \
            --build-arg TICKER=SAPP \
            --build-arg NAME=Sapphire \
            --build-arg BASE_NAME=sapphire \
            --build-arg TARGET=master \
            -t SAPP-linux-x64-build \
            -f contrib/docker/Dockerfile.dsw-linux-x64-wallet .

          # Start the container (if it's not already running)
          docker run -d --name SAPP-linux-x64-build-container SAPP-linux-x64-build

          # Create a temporary directory to hold the extracted files
          mkdir release_files

          # Copy files from the Docker container to the local filesystem
          docker cp SAPP-linux-x64-build-container:/SAPP/deploy/linux-x64 release_files/

      - name: Archive and Upload Extracted Files
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: release_files
